#server:
#  port: 8080
#
#eureka:
#  instance:
#      leaseRenewalIntervalInSeconds: 1
#      leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.99.100:9090/eureka/
#
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  actuator:
#    sensitive: false
#
#zuul:
#  routes:
#    testservice:
#      path: /test/**